hmcts/idam-testing-support-api

build.gradle
N/A
Update tomcat embed
```
[ ] Yes
[X] No
```
=> update tomcat embed

build.gradle
N/A
Fix jacoco by removing integration (fingers crossed)
```
[ ] Yes
[X] No
```
=> remove more of integration

build.gradle
N/A
fix main class
```
[ ] Yes
[X] No
```
=> fix main class

Dockerfile, charts/idam-testing-support-api/Chart.yaml, charts/idam-testing-support-api/values.yaml, docker-compose.yml, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/controllers/RootController.java, src/main/resources/application.yaml
Make it secure
```
[ ] Yes
[X] No
```
=> SIDM-7152 change ports

Jenkinsfile_CNP
Run all stages
```
[ ] Yes
[X] No
```
=> SIDM-7152 run all stages

Jenkinsfile_CNP, Jenkinsfile_parameterized
Paramaterize Sandbox
```
[ ] Yes
[X] No
```
=> sandbox paramaterized

Jenkinsfile_parameterized
N/A
Add sandbox subscription
```
[ ] Yes
[X] No
```
=> add subscription

infrastructure/main.tf
setup db for preview or sandbox
```
[ ] Yes
[X] No
```
=> SIDM-7152 setup db for preview or sandbox

infrastructure/main.tf
N/A
shorter name
```
[ ] Yes
[X] No
```
=> shorter name

build.gradle, charts/idam-testing-support-api/Chart.yaml, charts/idam-testing-support-api/values.preview.template.yaml, src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/model/AccountStatus.java, src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/model/ActivatedUserRequest.java, src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/model/User.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/config/DocConfig.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/controllers/RootController.java
Initial services and app insight logging
```
[ ] Yes
[X] No
```
=> SIDM-7152 initial services and app insight logging

build.gradle
N/A
ignore sonar temporarily
```
[ ] Yes
[X] No
```
=> ignore sonar temporarily

build.gradle
downgrade log version
```
[ ] Yes
[X] No
```
=> SIDM-7152 downgrade log version

build.gradle
N/A
Merge preview
```
[ ] Yes
[x] No
```
=> Merge Preview

charts/idam-testing-support-api/Chart.yaml, charts/idam-testing-support-api/values.yaml, src/main/resources/application.yaml
get app insight key from vault
```
[ ] Yes
[X] No
```
=> SIDM-7152 get app insight key from vault

src/main/resources/logback-includes.xml
info app insights
```
[ ] Yes
[X] No
```
=> info app insight logs

charts/idam-testing-support-api/Chart.yaml, charts/idam-testing-support-api/values.yaml
Release name override
```
[ ] Yes
[X] No
```
=> release name override

charts/idam-testing-support-api/Chart.yaml, charts/idam-testing-support-api/values.yaml
Add globals
```
[ ] Yes
[X] No
```
=> add global

src/main/resources/application.yaml
Add configtree
```
[ ] Yes
[X] No
```
=> add configtree

.gitignore, build.gradle, charts/idam-testing-support-api/Chart.yaml, charts/idam-testing-support-api/values.yaml, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/config/DocConfig.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/config/SecurityConfig.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/controllers/RootController.java, src/main/resources/application.yaml
configure as oauth2 resource server
```
[ ] Yes
[X] No
```
=> configure as oauth2 resource server

build.gradle
Update spring boot
```
[ ] Yes
[X] No
```
=> update spring boot

build.gradle, config/owasp/suppressions.xml
remove pmd, suppress oddity
```
[ ] Yes
[X] No
```
=> remove pmd, suppress oddity

src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/error/SpringWebClientErrorDecoder.java, src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/error/SpringWebClientHelper.java, src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/error/SpringWebClientRetryer.java, src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/health/DependencyHealthIndicator.java, src/main/resources/application.yaml
convert feign errors to spring errors
```
[ ] Yes
[X] No
```
=> convert feign errors to spring errors

src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/api/HealthApi.java, src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/health/DependencyHealthIndicator.java
health use only exceptions
```
[ ] Yes
[X] No
```
=> health use only exceptions

build.gradle, charts/idam-testing-support-api/Chart.yaml, charts/idam-testing-support-api/values.yaml, src/main/resources/application.yaml, src/main/resources/db/migration/V2022_03_17_1614__initial_db.sql
Add flyway and initial schema
```
[ ] Yes
[X] No
```
=> add flyway and initial schema

charts/idam-testing-support-api/Chart.yaml, charts/idam-testing-support-api/values.aat.template.yaml, charts/idam-testing-support-api/values.preview.template.yaml, charts/idam-testing-support-api/values.sandbox.template.yaml
N/A
fix release name
```
[ ] Yes
[X] No
```
=> fix release name

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/SIDM-7276
Deploy infrastructure everywhere except prod
```
[ ] Yes
[X] No
```
=> SIDM-7276 deploy infrastructure everywhere except prod

build.gradle, charts/idam-testing-support-api/Chart.yaml, charts/idam-testing-support-api/values.yaml, src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/error/SpringWebClientHelper.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/config/NotifyConfig.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/controllers/NotificationsController.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/NotificationsService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/controllers/NotificationsControllerTest.java, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/NotificationsServiceTest.java
https://tools.hmcts.net/jira/browse/SIDM-7277
Add get latest notification endpoint
```
[ ] Yes
[X] No
```
=> SIDM-7277 search for notifications

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/cft/idam/notify/IdamNotificationClient.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/config/NotifyConfig.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/NotificationsService.java, src/test/java/uk/gov/hmcts/cft/idam/notify/IdamNotificationClientTest.java, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/NotificationsServiceTest.java
https://tools.hmcts.net/jira/browse/SIDM-7277
Wrap NotificationClient to include useful things
```
[ ] Yes
[X] No
```
=> SIDM-7277 wrap notify client

src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/model/AccountStatus.java, src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/model/RecordType.java, src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/model/User.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/IdamV0Service.java, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/IdamV0ServiceTest.java
https://tools.hmcts.net/jira/browse/SIDM-7114
Update user model
```
[ ] Yes
[X] No
```
=> SIDM-7114 add record type to user model

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/SIDM-6510
Change cleanup lifespans
```
[ ] Yes
[X] No
```
=> SIDM-6150 update lifespans

src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/controllers/UserController.java, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/controllers/UserControllerTest.java
N/A
add simple logging for create user
```
[ ] Yes
[X] No
```
=> add simple logging for create user

build.gradle, config/checkstyle/suppressions.xml, src/main/java/uk/gov/hmcts/cft/idam/api/v2/IdamV2ConfigApi.java, src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/model/ServiceProvider.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/controllers/AdminController.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/controllers/ServiceProviderController.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/internal/InternalAdminApi.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/receiver/CleanupReceiver.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/AdminService.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingEntityService.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingServiceProviderService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/controllers/ServiceProviderControllerTest.java, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/receiver/CleanupReceiverTest.java, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/AdminServiceTest.java, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingEntityServiceTest.java, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingServiceProviderServiceTest.java
https://tools.hmcts.net/jira/browse/SIDM-7910
Create test services
```
[ ] Yes
[X] No
```
=> Sidm 7910 create test services

build.gradle, charts/idam-testing-support-api/Chart.yaml, charts/idam-testing-support-api/values.preview.template.yaml, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingUserService.java
https://tools.hmcts.net/jira/browse/SIDM-7999
Use the correct entity for getting user id, and fix a cve
```
[ ] Yes
[X] No
```
=> SIDM-7999 use entity that has id, and cve fix

build.gradle
N/A
Bump versions
```
[ ] Yes
[X] No
```
=> bump versions

build.gradle, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/config/SchedulerConfig.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/controllers/UserController.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/repo/TestingEntityRepo.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/repo/TestingSessionRepo.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingEntityService.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingSessionService.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingUserService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/controllers/UserControllerTest.java, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingEntityServiceTest.java, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingSessionServiceTest.java, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingUserServiceTest.java
https://tools.hmcts.net/jira/browse/SIDM-8188
Make cleanup batch sizes configurable
Request removal of test users by id (bring any idam user into testing support cleanup)
```
[ ] Yes
[X] No
```
=> cleanup batch sizes

src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/config/DocConfig.java
N/A
add swagger for services and roles
```
[ ] Yes
[X] No
```
=> add swagger for services and roles

Jenkinsfile_CNP, charts/idam-testing-support-api/Chart.yaml, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/controllers/UserController.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingUserService.java, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/controllers/UserControllerTest.java, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingUserServiceTest.java
https://tools.hmcts.net/jira/browse/SIDM-8408
Add get user endpoint
```
[ ] Yes
[X] No
```
=> SIDM-8408 add get user

.github/dependabot.yml, build.gradle, src/main/java/uk/gov/hmcts/cft/idam/api/v2/IdamV2UserManagementApi.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/controllers/RoleController.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/controllers/ServiceProviderController.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/controllers/UserController.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/AdminService.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingEntityService.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingUserService.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/trace/TraceAttribute.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/controllers/UserControllerTest.java, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingEntityServiceTest.java, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingUserServiceTest.java
https://tools.hmcts.net/jira/browse/SIDM-8455
Update users and remove roles and services
```
[ ] Yes
[X] No
```
=> SIDM-8455 update users and remove roles and services

build.gradle, charts/idam-testing-support-api/Chart.yaml, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/receiver/CleanupReceiver.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/AdminService.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingEntityService.java, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/AdminServiceTest.java, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingEntityServiceTest.java
N/A
handle nothing to delete
```
[ ] Yes
[X] No
```
=> handle nothing to delete

build.gradle, charts/idam-testing-support-api/Chart.yaml, config/owasp/suppressions.xml, gradle/wrapper/gradle-wrapper.properties, src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/model/User.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/repo/TestingEntityRepo.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/repo/model/TestingState.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/AdminService.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingEntityService.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingUserService.java, src/main/resources/application.yaml, src/main/resources/db/migration/V2023_05_07_1005__add_state.sql, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/AdminServiceTest.java, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingEntityServiceTest.java, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingUserServiceTest.java
https://tools.hmcts.net/jira/browse/SIDM-8787
Implement different cleanup strategy for users that are still in use
```
[ ] Yes
[X] No
```
=> SIDM-8787 Delete if Dormant cleanup strategy

build.gradle, src/functionalTest/java/uk/gov/hmcts/cft/idam/testingsupportapi/UserApiIntegrationTest.java
https://tools.hmcts.net/jira/browse/SIDM-8904
fix serenity
```
[ ] Yes
[X] No
```
=> SIDM-8904 fix serenity

.github/renovate.json, renovate.json
https://tools.hmcts.net/jira/browse/SIDM-8846
fix renovate
```
[ ] Yes
[X] No
```
=> fix renovate

build.gradle
Reverts hmcts/idam-testing-support-api#356
=> Revert "Update dependency checkstyle to v10"

src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingCaseWorkerProfileService.java
https://tools.hmcts.net/jira/browse/SIDM-8919
Add location
```
[ ] Yes
[X] No
```
=> add location desc

src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingCaseWorkerProfileService.java
https://tools.hmcts.net/jira/browse/SIDM-8901
Add caseworker service
```
[ ] Yes
[X] No
```
=> SIDM-8901 add service description

lib/applicationinsights.json
https://tools.hmcts.net/jira/browse/SIDM-8987
log sampling
```
[ ] Yes
[x] No
```
=> SIDM-8987 log sample

src/main/java/uk/gov/hmcts/cft/idam/api/v2/IdamV2InvitationApi.java, src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/model/Invitation.java, src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/model/InvitationStatus.java, src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/model/InvitationType.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/controllers/InvitationController.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingInvitationService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/controllers/InvitationControllerTest.java, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingInvitationServiceTest.java
https://tools.hmcts.net/jira/browse/SIDM-9057
Get invitations through testing support
```
[ ] Yes
[x] No
```
=> SIDM-9057 get invitations

src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/NotificationsService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/NotificationsServiceTest.java
https://tools.hmcts.net/jira/browse/SIDM-9111
make notify max pages configurable
```
[ ] Yes
[x] No
```
=> SIDM-9111 make notify max pages configurable

Jenkinsfile_CNP
N/A
Update to sync preview with master after build
```
[ ] Yes
[X] No
```
=> Update to sync preview with master after build

src/functionalTest/java/uk/gov/hmcts/cft/idam/testingsupportapi/UserApiIntegrationTest.java, src/functionalTest/java/uk/gov/hmcts/cft/idam/testingsupportapi/steps/UserSteps.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/controllers/UserController.java, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/controllers/UserControllerTest.java
N/A
Get user by email
```
[ ] Yes
[X] No
```
=> get user by email

README.md, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/receiver/CleanupReceiver.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingEntityService.java
https://tools.hmcts.net/jira/browse/SIDM-9097
Add some logging
```
[ ] Yes
[X] No
```
=> SIDM-9097 add logging

build.gradle
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
https://tools.hmcts.net/jira/browse/DTSCS-1010
Removed dependency on the deprecated library `properties-volume-spring-boot-starter`.
```
[ ] Yes
[x] No
```
=> DTSCS-1010: Remove unused dependency

src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/config/QueueConfig.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/receiver/CleanupReceiver.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/trace/TraceAttribute.java
Prevent retries
```
[ ] Yes
[x] No
```
=> SIDM-9145 prevent retries

src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/config/SchedulerConfig.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/repo/TestingEntityRepo.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/AdminService.java
lock burner users for update
```
[ ] Yes
[X] No
```
=> SIDM-9145 lock burner users for update

src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/receiver/CleanupReceiverTest.java
Improve coverage
```
[ ] Yes
[X] No
```
=> SIDM-9145 improve coverage

src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/config/QueueConfig.java
Make concurrency configurable
```
[ ] Yes
[X] No
```
=> SIDM-9145 Make concurrency configurable

src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/config/QueueConfig.java
checkstyle
```
[ ] Yes
[X] No
```
=> SIDM-9145 checkstyle

Jenkinsfile_CNP, build.gradle, charts/idam-testing-support-api/Chart.yaml, charts/idam-testing-support-api/values.aat.template.yaml, charts/idam-testing-support-api/values.preview.template.yaml, charts/idam-testing-support-api/values.yaml, src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/ratelimit/RateLimitService.java, src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/ratelimit/TokenBucket.java, src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/ratelimit/TokenBucketConfiguration.java, src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/ratelimit/TokenBucketRepo.java, src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/ratelimit/TokenBucketRepoImpl.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/config/CacheConfig.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/config/RateLimitConfig.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/controllers/AdminController.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/properties/RateLimitProperties.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/AdminService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/AdminServiceTest.java
rate limit burner expiry
Note that most of the rate limit code comes from idam-api which is where the tests for it are. Ideally we'd move this kind of common stuff into one of the dev toolset libraries.
```
[ ] Yes
[X] No
```
=> SIDM-9145 rate limit burner expiry

src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/controllers/ServiceProviderController.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingEntityService.java, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingEntityServiceTest.java
https://tools.hmcts.net/jira/browse/SIDM-9466
Detach all conflicting services
```
[ ] Yes
[X] No
```
=> SIDM-9466 detach all conflicting services

src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/repo/TestingSessionRepo.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingSessionService.java, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingSessionServiceTest.java
Support 
handle session key duplicates
```
[ ] Yes
[X] No
```
=> handle session key duplicates

charts/idam-testing-support-api/Chart.yaml, charts/idam-testing-support-api/values.yaml
https://tools.hmcts.net/jira/browse/SIDM-9496
Use new secrets and bump chart
```
[ ] Yes
[X] No
```
=> SIDM-9496 use new secrets and bump chart

charts/idam-testing-support-api/Chart.yaml, charts/idam-testing-support-api/values.yaml
https://tools.hmcts.net/jira/browse/SIDM-9496
Use new secrets and bump chart
```
[ ] Yes
[X] No
```
=> SIDM-9496 use new secrets and bump chart (again)

charts/idam-testing-support-api/Chart.yaml
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
=> CME-436:HELM OCI IDAM -idam-testing-support-api/Chart.yaml

build.gradle, src/main/java/uk/gov/hmcts/cft/idam/api/v1/common/model/V1User.java, src/main/java/uk/gov/hmcts/cft/idam/api/v1/common/util/UserConversionUtil.java, src/main/java/uk/gov/hmcts/cft/idam/api/v2/IdamV2UserManagementApi.java, src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/auth/IdamClientCredentialsConfig.java, src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingUserService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/TestingUserServiceTest.java
https://tools.hmcts.net/jira/browse/SIDM-9759
Create archived users directly
```
[ ] Yes
[X] No
```
=> SIDM-9759 create archived users directly

src/main/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/AdminService.java, src/test/java/uk/gov/hmcts/cft/idam/testingsupportapi/service/AdminServiceTest.java
https://tools.hmcts.net/jira/browse/SIDM-9773
Add cleanup logging for precondition failures
```
[ ] Yes
[X] No
```
=> SIDM-9773 add cleanup logging for precondition failures
